steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'cp'
      - 'gs://q-rice/service-account-key.json'
      - './service-account-key.json'

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia-southeast2-docker.pkg.dev/q-rice/q-rice-repo/ml-image:$SHORT_SHA', 
           '.']
    
    # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'asia-southeast2-docker.pkg.dev/q-rice/q-rice-repo/ml-image:$SHORT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'q-rice'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/q-rice/q-rice-repo/ml-image:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'

options:
  logging: CLOUD_LOGGING_ONLY